name: leviosa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  better_player: ^0.0.84
  cached_network_image: ^3.4.1
  calendar_view: null
  camera: ^0.11.0+2
  cloud_firestore: ^5.5.0
  file_picker: ^8.1.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cube: ^0.1.1
  flutter_native_splash: ^2.4.3
  flutter_tts: ^4.0.2
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  http: ^1.2.1
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: ^27.2.4
  translator: null
  youtube_player_iframe: ^5.1.5
  zego_uikit_prebuilt_call: ^4.15.12
  zego_uikit_prebuilt_live_streaming: ^3.12.8
  zego_uikit_signaling_plugin: ^2.8.4
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/file/
    - assets/bg/
    - assets/level_1/
    - assets/level_2/
    - assets/music/

icons_launcher:
  image_path: "assets/img/leviosa-icon.jpeg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#000000"
  image: assets/img/leviosa-icon.jpeg
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: assets/img/leviosa-icon.jpeg
    color: "#000000"
    icon_background_color: "#000000"
    image_dark: assets/img/leviosa-icon.jpeg
    icon_background_color_dark: "#000000"
