name: leviosa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  cached_network_image: ^3.4.1
  calendar_view:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  go_router: ^14.6.0
  signature: ^5.5.0

  intl: ^0.19.0
  youtube_player_iframe: ^5.1.5


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

icons_launcher:
  image_path: "assets/img/leviosa-icon.jpeg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#000000"
  image: assets/img/leviosa-icon.jpeg
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: assets/img/leviosa-icon.jpeg
    color: "#000000"
    icon_background_color: "#000000"
    image_dark: assets/img/leviosa-icon.jpeg
    icon_background_color_dark: "#000000"
